-- MySQL Script generated by MySQL Workbench
-- Thu Jun 16 11:56:03 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema Hotel_Booking
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema Hotel_Booking
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `Hotel_Booking` DEFAULT CHARACTER SET utf8 ;
USE `Hotel_Booking` ;

-- -----------------------------------------------------
-- Table `Hotel_Booking`.`Booking`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Hotel_Booking`.`Booking` ;

CREATE TABLE IF NOT EXISTS `Hotel_Booking`.`Booking` (
  `User_ID` INT NOT NULL,
  `Start_Date` DATE NULL,
  `End_Date` DATE NULL,
  `Room_ID` VARCHAR(45) NULL,
  PRIMARY KEY (`User_ID`))
ENGINE = InnoDB;

LOCK TABLES `Booking` WRITE;
/*!40000 ALTER TABLE `Booking` DISABLE KEYS */;
-- sample data
INSERT INTO `Booking`
VALUES
(1,'2022-6-16','2022-6-20',1),
(3,'2021-6-16','2021-6-20',2),
(2,'2023-6-16','2023-6-20',3);
/*!40000 ALTER TABLE `Booking` ENABLE KEYS */;
UNLOCK TABLES;

-- -----------------------------------------------------
-- Table `Hotel_Booking`.`Rooms`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Hotel_Booking`.`Rooms` ;

CREATE TABLE IF NOT EXISTS `Hotel_Booking`.`Rooms` (
  `Room_ID` INT AUTO_INCREMENT NOT NULL,
  `Type` VARCHAR(10) NOT NULL,
  `image` VARCHAR(100) NULL DEFAULT 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRgvttt3kj4ULLoJk1l3ZklSMW1RiGcXFfjYg&usqp=CAU',
  `description` VARCHAR(100) NULL DEFAULT '',
  PRIMARY KEY (`Room_ID`),
  UNIQUE INDEX `Room_ID_UNIQUE` (`Room_ID` ASC) VISIBLE,
  UNIQUE INDEX `image_UNIQUE` (`image` ASC) VISIBLE)
ENGINE = InnoDB;

LOCK TABLES `Rooms` WRITE;
/*!40000 ALTER TABLE `Rooms` DISABLE KEYS */;
INSERT INTO `Rooms` VALUES (1,'Single','https://www.frasershospitality.com/content/dam/frasers-hospitality/english/properties/united-kingdom/south-kensington/park-international-hotel-south-kensington/images/gallery-images/rooms/room-type-main-images/single-room/PIHL_Single%20Room.jpg', 'Single bedroom'), (2,'Double','https://d2ile4x3f22snf.cloudfront.net/wp-content/uploads/sites/179/2018/09/07040236/Superior_Double_Double-800x436.jpg', 'A double bed room'), (3,'Deluxe','https://www.marinabaysands.com/content/dam/singapore/marinabaysands/master/main/home/hotel/rooms-suites/deluxe-room/deluxe-1_1920x960.jpg', 'Deluxe room woohoo');
/*!40000 ALTER TABLE `Rooms` ENABLE KEYS */;
UNLOCK TABLES;

-- -----------------------------------------------------
-- Table `Hotel_Booking`.`Users`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Hotel_Booking`.`Users` ;

CREATE TABLE IF NOT EXISTS `Hotel_Booking`.`Users` (
  `User_ID` INT AUTO_INCREMENT NOT NULL,
  `Username` VARCHAR(16) NOT NULL,
  `Password` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`User_ID`),
  UNIQUE INDEX `User_ID_UNIQUE` (`User_ID` ASC) VISIBLE,
  UNIQUE INDEX `Username_UNIQUE` (`Username` ASC) VISIBLE)
ENGINE = InnoDB;

LOCK TABLES `Users` WRITE;
/*!40000 ALTER TABLE `Users` DISABLE KEYS */;
INSERT INTO `Users`
VALUES
(1,'ryan','uwu'),
(2,'christina','uwu'),
(3,'peter','uwu');
/*!40000 ALTER TABLE `Users` ENABLE KEYS */;
UNLOCK TABLES;

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;


